### ISSUE TITLE
使用SID无法收敛

### ISSUE THREAD

**Issue by henryccl** [SiaStg/SiaStegNet#3]
您好 我在使用您的代码对bossbase (S-Uniward0.4)进行训练时发现，使用KeNet可以收敛， 使用SID无法收敛。这个代码里面的SID应该就是YeNet对吧？在对SID进行训练时，需要注意些什么吗？我在训练SID时就只把args.model的值从'kenet'  变成了'sid'。然后进行训练发现不能收敛，如何正常对SID进行训练呢？求解答！！

**Comment by FuckingNoO** [comment]
> 您好 我在使用您的代码对bossbase (S-Uniward0.4)进行训练时发现，使用KeNet可以收敛， 使用SID无法收敛。这个代码里面的SID应该就是YeNet对吧？在对SID进行训练时，需要注意些什么吗？我在训练SID时就只把args.model的值从'kenet' 变成了'sid'。然后进行训练发现不能收敛，如何正常对SID进行训练呢？求解答！！

我的是KeNet是无法收敛

**Comment by zjhJOJO** [comment]
> 您好 我在使用您的代码对bossbase (S-Uniward0.4)进行训练时发现，使用KeNet可以收敛， 使用SID无法收敛。这个代码里面的SID应该就是YeNet对吧？在对SID进行训练时，需要注意些什么吗？我在训练SID时就只把args.model的值从'kenet' 变成了'sid'。然后进行训练发现不能收敛，如何正常对SID进行训练呢？求解答！！

SID 应该不是YeNet, 请参考文章的参考文献[29], 另外你的问题解决了吗？

**Comment by henryccl** [comment]
> > 您好 我在使用您的代码对bossbase (S-Uniward0.4)进行训练时发现，使用KeNet可以收敛， 使用SID无法收敛。这个代码里面的SID应该就是YeNet对吧？在对SID进行训练时，需要注意些什么吗？我在训练SID时就只把args.model的值从'kenet' 变成了'sid'。然后进行训练发现不能收敛，如何正常对SID进行训练呢？求解答！！
> 
> SID 应该不是YeNet, 请参考文章的参考文献[29], 另外你的问题解决了吗？

我换了一个新的baseline，绕过了这个问题
